server:
  port: 443
  http2:
    enabled: true
  servlet:
    context-path: /
  ssl:
    key-store: classpath:www.csnight.xyz.pfx
    key-store-password: myJ5h6ik
    key-store-type: PKCS12
spring:
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # generate_statistics: true #sql统计
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rmsdb?serverTimezone=Asia/Shanghai
    username: csnight
    password: qnyh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      aop-patterns: csnight.redis.monitor.rest.*
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      web-stat-filter:
        enabled: true
        session-stat-max-count: 10
        profile-enable: true
      stat-view-servlet:
        enabled: true
        reset-enable: true
        allow:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: redis_monitor
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
            misfireThreshold: 5000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: false
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:qrtz.sql
  servlet:
    multipart:
      max-file-size: 2MB
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=1000,maximumSize=2000,expireAfterWrite=60s,recordStats
logging:
  config: classpath:logback-config.xml
websocket:
  server: 127.0.0.1
  port: 13244
dumpdir:
  conf-dir: tools/configs
  record-dir: tools/backups
  exec-dir: tools/shakeBin
rms-log:
  executors: mysql
  elastic:
    addresses: http://127.0.0.1:9200
#logging:
#  config: classpath:log4j2-spring.xml